version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "rizq_nasional"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 

  springboot-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rizq_nasional
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
