name: Build & Push

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Github Container Registry
        run: echo ${{ secrets.PRIVATE_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/rizq-api:latest ./rizq-nasional-website

      - name: Push Docker image to ghcr.io
        run: docker push ghcr.io/${{ github.repository_owner }}/rizq-api:latest
