
name: Deployment

on:
  workflow_run:
    workflows: [Build & Push]
    types:
      - completed

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd /var/docker/be-rizqnasional
            make down && make up
